import random
import re

f= open('autoGeneratedData.txt', 'w')

words = ["THISISA40CHARACTERSTRINGNOTAPHRASEMMKAY?", "apple", "orange", "[taco bell]", "America", "Listing", "Fontenot", "[Data Structures]", "Millipede", "colorado", "denver", "ColOrADo", "Mildred", "Mouse", "[Linux Box]", "Search", "[234 Tree]", "[99 Bottles of Beer]", "[40 Character Word or Phrase89123456789@]", "[Burger king]", "[BuRGeR KiNg]"]

for i in range(1000):
    f.write("<" + str(random.randint(1,1000)) + ">\n")
    daString = ""
    for j in range(random.randint(1,100)):
        daTempString = words[random.randint(0, len(words)-1)] + " "
        if(len(daString) + len(daTempString) < 80):
            daString += daTempString
        else:
            f.write(daString + "\n")
            daString = ""
    if(len(daString) > 0):
        f.write(daString + "\n")
    

f.write("<-1>")

f.close()

print (len(s) + ", " for s in words)
for s in words:
    print str(len(s)) + ", "
